runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: 'your_secure_random_secret_key'

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
