runtime: python39

entrypoint: gunicorn -b :$PORT app:app  # Menjalankan aplikasi Flask dengan Gunicorn

env_variables:
  SECRET_KEY: 'your_secure_random_secret_key'  # Ganti dengan secret key yang kuat

handlers:
  - url: /static
    static_dir: static/  # Mengarahkan folder static ke URL /static (untuk file CSS, JS, gambar, dll)
  
  - url: /.*  # Semua URL lain diarahkan ke aplikasi Flask
    script: auto  # Menangani semua request dengan aplikasi Flask

automatic_scaling:
  target_cpu_utilization: 0.65  # Menentukan target penggunaan CPU
  min_instances: 1  # Jumlah minimal instance aplikasi yang berjalan
  max_instances: 10  # Jumlah maksimal instance aplikasi yang berjalan
